# src/steam_report_grader/llm/cluster_prompts.py
from __future__ import annotations
from textwrap import dedent
from typing import List


def build_cluster_summary_and_ai_template_prompt(
    question_label: str,
    question_text: str,
    rubric_text: str,
    sample_answers: List[str],
) -> str:
    """
    クラスター内の代表的な回答群を渡して、
    - クラスター要約
    - AIテンプレ度
    を評価させるプロンプト。
    """
    # サンプルを区切って渡す
    joined_answers = "\n\n---\n\n".join(sample_answers)

    prompt = f"""
You are an expert in educational assessment and writing style analysis.
Below are multiple students’ answers to the same question.
These answers form a cluster of “responses with similar style.”

[Question ID]
{question_label}

[Question]
{question_text.strip()}

[Overview of the Rubric]
{rubric_text.strip()[:800]}

[Sample Answers in This Cluster]
{joined_answers}

Task:
1. Summarize the characteristics of the answers in this cluster from the following perspectives:
   - Content: what the students are writing about
   - Structure: paragraph organization and logical flow
   - Style: level of formality, vocabulary, formulaic expressions, etc.

2. Rate how similar the answers in this cluster are to a “template-like response generated by AI (e.g., ChatGPT, Gemini),”
   using a score from 0.0 to 1.0.
   - Scores close to 1.0: very “AI-template-like”
   - Scores close to 0.0: more “human-like” with noticeable variation

3. Explain, in a way that is easy for teachers to understand, why you chose that score.

Your output must be "ONLY" the following JSON format. Do not write any additional explanations or text.

    {{
  "summary": "A summary of the characteristics of this cluster",
  "ai_template_likeness": number,
  "comment": "An explanation of how AI-template-like these answers are"
    }}
    """
    return dedent(prompt).strip()
